name: Build App

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  Build:

    strategy:
      matrix:
        runtime: [win-x64, win-x86, win-arm64, linux-x64, linux-arm64, linux-arm, osx-x64, osx-arm64]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      env:
        platform: ${{ matrix.runtime }}
      run: dotnet publish WhoIsLive.UX.Desktop -c Release -r ${{ matrix.runtime }} -o build/ux/${{ matrix.runtime }}

    - name: Remove PDB files
      run: |
        find ./build/ux/${{ matrix.runtime }} -name '*.pdb' -type f -delete

    - name: Generate artifact name
      env:
        platform: ${{ matrix.runtime }}
      run: echo "artifact_name=WhoIsLive-${{ matrix.runtime }}" >> $GITHUB_ENV

    - uses: actions/upload-artifact@main
      name: Upload artifact
      with:
        name: ${{ env.artifact_name }}
        path: build/ux/${{ matrix.runtime }}